import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const account=await readFile(new URL('account.html',root),'utf8');
const auth=await readFile(new URL('src/auth.js',root),'utf8');
const accountJs=await readFile(new URL('src/account.js',root),'utf8');
const login=await readFile(new URL('login.html',root),'utf8');
const privacy=await readFile(new URL('privacy.html',root),'utf8');
const admin=await readFile(new URL('src/admin-users.js',root),'utf8');
const cleanup=await readFile(new URL('supabase/migrations/005_remove_member_location_data.sql',root),'utf8');
const css=await readFile(new URL('styles.css',root),'utf8');
assert.match(account,/data-auth-link/);
assert.match(account,/preference-dropdown/);
assert.match(account,/favoriteMarkets/);
assert.match(account,/favoriteLeagues/);
assert.doesNotMatch(account,/locationOptIn|Share my approximate area|Update location choice/);
assert.match(auth,/profile-avatar-button/);
assert.match(auth,/getAvatarUrl/);
assert.match(auth,/user_metadata\?\.avatar_url/);
assert.match(auth,/refreshProfile/);
assert.doesNotMatch(auth,/navigator\.geolocation|captureApproxLocation/);
assert.doesNotMatch(login,/shareLocation|Share a broad area/);
assert.doesNotMatch(admin,/Broad area|Permission not granted/);
assert.match(privacy,/does not request GPS/);
assert.match(css,/account-loading\[hidden\]/);
assert.match(css,/profile-avatar-button/);
assert.match(accountJs,/Promise\.allSettled/);
assert.match(cleanup,/approx_lat = null/);
assert.match(cleanup,/location_opt_in = false/);
console.log('v21.0.0 account avatar and preference checks passed');
