import assert from 'node:assert/strict';
import fs from 'node:fs';
const handoff=fs.readFileSync(new URL('../src/handoff.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../responsive.css',import.meta.url),'utf8');
const stability=fs.readFileSync(new URL('../src/stability.js',import.meta.url),'utf8');
const account=fs.readFileSync(new URL('../account.html',import.meta.url),'utf8');
const login=fs.readFileSync(new URL('../login.html',import.meta.url),'utf8');
assert.match(handoff,/sporty-handoff/);
assert.match(handoff,/logo-mark\.webp/);
assert.match(handoff,/logo-wordmark-dark\.webp/);
assert.match(handoff,/window\.location\.assign/);
assert.match(css,/html\[data-theme="light"\] \.codehub-banner/);
assert.match(css,/\.sporty-handoff\.show/);
assert.match(css,/\.trust-strip\{display:none!important\}/);
assert.doesNotMatch(account,/Opening your account/);
assert.doesNotMatch(account,/Broad area only/);
assert.doesNotMatch(login,/No backend details exposed/);
assert.doesNotMatch(login,/Presence <strong>Active/);
assert.doesNotMatch(stability,/Data confidence summary/);
console.log('v20.1 clean theme, simplified account and handoff checks passed');
