import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile(new URL('../src/elite.js',import.meta.url),'utf8');
const document={addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}};
const window={};
const context={window,document,console,fetch:async()=>({ok:false}),setTimeout,clearTimeout,Date,Math,Number,String,Set,Map,CustomEvent:class{}};
vm.createContext(context);vm.runInContext(source,context);
const bridge=window.__SPORTY_ELITE_BRIDGE_TEST__;
assert.ok(bridge,'Elite bridge helpers must be exposed');
const base={boardEligible:true,key:'today|a|goals|over15',fixture:'Alpha vs Beta',market:'Total Goals',pick:'Over 1.5',league:'Test',kickoff:new Date(Date.now()+3600000).toISOString(),rawShare:70,appearances:6,independent:5,uniqueSources:6,oppositionShare:5,averageOdds:1.25,dataCompleteness:96,marketFit:100,statsSupport:{available:true,score:84},stability:{available:true,score:88,observations:4},history:{available:true,score:76,sample:12}};
let rows=bridge.deriveLiveItems([base]);
assert.equal(rows.length,1);assert.equal(rows[0].classification,'elite_strong');assert.match(rows[0].reason,/verified booking codes/);
rows=bridge.deriveLiveItems([{...base,appearances:3,independent:3,uniqueSources:3,rawShare:45,statsSupport:{available:true,score:69},oppositionShare:18}]);
assert.equal(rows[0].classification,'elite_supported');
rows=bridge.deriveLiveItems([{...base,appearances:2,independent:2,uniqueSources:2,rawShare:28,statsSupport:{available:false,score:0},stability:{available:false,score:0},history:{available:false,score:0},marketFit:78,dataCompleteness:78,oppositionShare:20}]);
assert.equal(rows[0].classification,'elite_watch');
rows=bridge.deriveLiveItems([{...base,oppositionShare:55}]);assert.equal(rows.length,0,'strong opposition must block Elite publication');
console.log('Elite Most Added bridge v21.7.4 tests passed.');
