import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const globalCss=read('styles.css');
const page=read('elite-picks.html');
const boardJs=read('src/elite-board-v2.js');
const boardCss=read('elite-board-v2.css');
const home=read('index.html');
const server=read('server/index.mjs');

assert.match(globalCss,/\[hidden\]\{display:none!important\}/,'native hidden must continue to hide empty sections');
assert.match(home,/href="\/elite-picks\.html"><b>◆<\/b><span>Elite<\/span>/,'mobile home navigation must include Elite');
assert.match(page,/data-page="elite-v2"/,'Elite page must use the standalone surface');
assert.match(page,/Elite Picks\./,'clear Elite Picks hero must be present');
assert.match(page,/elite-board-v2\.css\?v=22\.2\.0/,'Elite page must load the shareable-slip stylesheet');
assert.match(page,/elite-board-v2\.js\?v=22\.2\.0/,'Elite page must load the shareable-slip renderer');
assert.match(page,/color-scheme" content="light dark"/,'Elite page must advertise both light and dark color schemes');
assert.match(page,/localStorage\.getItem\('sporty_theme'\)/,'Elite page must restore the saved Sporty theme before paint');
assert.match(page,/Supported picks/,'summary must distinguish supported selections from strong selections');
assert.match(page,/Create prediction slip/,'Elite hero must expose the prediction-slip builder');
assert.match(page,/src\/mvp\.js/,'Elite page must load shared tip normalization used by Smart Board');
assert.match(page,/src\/share\.js/,'Elite page must load the branded share-card engine');
assert.match(page,/src\/slip-builder\.js/,'Elite page must load the shared prediction-slip drawer');
assert.doesNotMatch(page,/src\/elite\.js/,'discarded legacy Elite renderer must not be loaded by the page');
assert.doesNotMatch(page,/elite-stats2pitch-bridge\.js/,'discarded Elite bridge must not be loaded by the page');
assert.match(page,/STATS2PITCH_ELITE_BOOTSTRAP/,'Elite page must retain the server bootstrap insertion point');
assert.match(boardJs,/\/api\/elite-picks\?limit=10&ts=/,'renderer must read the persisted Stats2Pitch API directly');
assert.match(boardJs,/embedded\.items\.length/,'renderer may use a non-empty server bootstrap without an extra request');
assert.match(boardJs,/predictionText/,'renderer must promote the actual prediction to the primary card line');
assert.match(boardJs,/Why this pick/,'long engine reasoning must sit behind an expandable explanation');
assert.match(boardJs,/data-elite-v2-filter/,'renderer must support market filtering');
assert.match(boardJs,/data-slip-add-key/,'Elite cards must expose shared slip-state keys');
assert.match(boardJs,/SportySlip\.add/,'Elite card actions must add picks to the shared Smart Board slip');
assert.match(boardJs,/SportySlip\.open/,'Elite page must open the shared prediction-slip drawer');
assert.match(boardCss,/--elite-red:#ff343d/,'Elite surface must use the Sporty red brand accent');
assert.match(boardCss,/\.elite-v2-slip-launch/,'Elite page must style the create-slip control');
assert.match(boardCss,/\.elite-v2-add-slip/,'Elite cards must style add-to-slip controls');
assert.match(boardCss,/html\[data-theme="light"\] body\[data-page="elite-v2"\]/,'Elite surface must provide dedicated light-theme overrides');
assert.match(boardCss,/--elite-bg:#f6f7f9/,'Elite light theme must use the Sporty white-page background');
assert.match(boardCss,/html\[data-theme="light"\] \.elite-v2-add-slip/,'Elite slip controls must remain legible in the white theme');
assert.match(boardCss,/@media\(max-width:600px\)/,'Elite Picks must include phone/Z Fold responsive rules');
assert.match(server,/elitePagePaths/,'server must intercept Elite page requests');
assert.match(server,/__SPORTY_ELITE_BOOTSTRAP__/,'server must embed the persisted Stats2Pitch Elite payload in the HTML response');
console.log('Elite Picks theme, clarity and shareable prediction-slip checks passed');
