import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const sw=read('service-worker.js');
const render=read('render.yaml');
const build=read('scripts/render-build.sh');
const server=read('server/index.mjs');
const mvp=read('src/mvp.js');
const intel=read('src/intelligence.js');
const pwa=read('src/pwa.js');
const css=read('styles.css');
const index=read('index.html');
assert.match(sw,/sporty-codes-v21\.4\.2/);
for(const cache of ['STATIC_CACHE','PAGE_CACHE','DATA_CACHE','IMAGE_CACHE'])assert.match(sw,new RegExp(`const ${cache}=`));
assert.match(sw,/stableDataRequest/);
assert.match(sw,/trimCache/);
assert.match(sw,/navigationPreload/);
assert.match(sw,/cacheFirst\(request,IMAGE_CACHE,70\)/);
assert.match(render,/runtime:\s*node/);
assert.match(server,/max-age=31536000, immutable/);
assert.match(server,/s-maxage=60, stale-while-revalidate=300/);
assert.match(server,/service-worker\.js/);
assert.match(mvp,/FEED_MIN_REFRESH_MS/);
assert.match(mvp,/feedLoadPromise/);
assert.match(mvp,/refreshFeedMetadata/);
assert.doesNotMatch(mvp,/feed-health\.json\?v=\$\{Date\.now\(\)\}/);
assert.doesNotMatch(mvp,/codehub-banner\.json[^\n]*Date\.now/);
assert.doesNotMatch(intel,/\?v=\$\{Date\.now\(\)\}/);
assert.match(pwa,/sporty_sw_update_checked_v209/);
assert.match(pwa,/6\*60\*60\*1000/);
assert.match(css,/content-visibility:auto/);
assert.match(css,/contain-intrinsic-size:auto 680px/);
assert.match(index,/styles\.css\?v=21\.4\.2/);
assert.match(build,/logo-wordmark-dark@2x\.png/);
assert.ok(fs.statSync(new URL('../favicon.svg',import.meta.url)).size<5000,'favicon should stay lightweight');
for(const file of ['logo-wordmark-dark.webp','logo-wordmark-light.webp','logo-mark.webp']){
  assert.ok(fs.statSync(new URL(`../assets/${file}`,import.meta.url)).size<26000,`${file} should be optimised`);
}
console.log('v20.9 performance optimisation checks passed');
