import { mkdir, writeFile, rename } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const text=value=>String(value??'').trim();
const env=(name,fallback='')=>text(process.env[name]??fallback);

async function writeJson(path,value){
  const full=resolve(path);
  const temporary=`${full}.tmp`;
  await mkdir(dirname(full),{recursive:true});
  await writeFile(temporary,`${JSON.stringify(value,null,2)}\n`,'utf8');
  await rename(temporary,full);
}

const generatedAt=new Date().toISOString();
const payload={
  version:4,
  generated_at:generatedAt,
  status:'replaced_by_stats2pitch_away_fav_streak',
  engine:'away-fav-streak-v1',
  source:'stats2pitch',
  count:0,
  elite_verified:0,
  elite_supported:0,
  trending:0,
  items:[],
  note:'Elite Picks are generated by Stats2Pitch Away-Fav Streak v1 and imported with sync:stats2pitch-elite. Booking-code consensus is no longer an Elite source.'
};

await writeJson(env('ELITE_OUTPUT_PATH','data/elite-picks.json'),payload);
await writeJson(env('ELITE_HEALTH_PATH','data/elite-feed-health.json'),{
  ok:true,
  generated_at:generatedAt,
  source:'stats2pitch-away-fav-streak-v1',
  count:0,
  replaced:true
});

console.log(JSON.stringify({ok:true,replaced:true,engine:'away-fav-streak-v1',count:0}));
