(()=>{
  'use strict';
  const $=s=>document.querySelector(s);const text=v=>String(v??'').trim();const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
  const el=(tag,cls,value)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(value!==undefined)node.textContent=String(value);return node};
  const clear=node=>{if(node)while(node.firstChild)node.removeChild(node.firstChild)};
  function price(value){const n=num(value);return n>1?n.toFixed(2):'—'}
  function when(row){const d=new Date(row.kickoff||num(row.start_time));if(!Number.isFinite(d.getTime()))return'Kickoff unavailable';return d.toLocaleString([], {weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
  function favorite(row){const rows=[['Home',num(row.oddsHome)],['Draw',num(row.oddsDraw)],['Away',num(row.oddsAway)]].filter(([,v])=>v>1).sort((a,b)=>a[1]-b[1]);return rows.length?`${rows[0][0]} is shortest at ${rows[0][1].toFixed(2)}`:'Odds not available yet'}
  function card(row){const article=el('article','market-board-card intelligence-card');const top=el('div','card-top');top.append(el('div','card-kicker',text(row.league)||'Football'),el('span','pill',when(row)));article.append(top,el('h3','',`${text(row.home_team)||'Home'} vs ${text(row.away_team)||'Away'}`));const odds=el('div','market-odds-grid');for(const [label,value] of [['1',row.oddsHome],['X',row.oddsDraw],['2',row.oddsAway]]){const box=el('div','metric');box.append(el('span','',label),el('strong','',price(value)));odds.append(box)}article.append(odds,el('p','card-note',favorite(row)));const source=el('div','market-source-row');source.append(el('span','live-status',text(row.odds_source||row.source||'custom-api').replace(/-/g,' ')),el('small','',text(row.country)||''));article.append(source);return article}
  function notice(title,copy){const box=el('article','market-board-empty');box.append(el('strong','',title),el('p','',copy));return box}
  async function load(){const section=$('#eventBoardSection'),root=$('#eventBoardGrid'),status=$('#eventBoardStatus');if(!section||!root||section.dataset.mode==='disabled')return;section.hidden=false;clear(root);root.append(notice('Loading public SportyBet matches…','The custom API is checking the cached public event feed.'));
    try{const response=await fetch('/api/get_upcoming_events?days=3',{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();const rows=Array.isArray(payload.events)?payload.events:[];clear(root);if(status)status.textContent=rows.length?`${rows.length} matches · ${text(payload.source).replace(/-/g,' ')}`:'No public matches returned';if(!rows.length){const reason=Array.isArray(payload.errors)&&payload.errors.length?payload.errors.join(' · '):'The public feed returned no recognized fixtures.';root.append(notice('No matches were parsed.',`${reason} Open /api/source-status for the exact response type and schema keys.`));return}rows.slice(0,60).forEach(row=>root.append(card(row)))}catch(error){clear(root);if(status)status.textContent='Source unavailable';root.append(notice('Match feed unavailable','The public SportyBet source did not respond. The consensus board will still appear whenever published booking-code selections are available.'))}}
  document.addEventListener('DOMContentLoaded',load);
  window.SportyMarketBoard={load};
})();
